apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: eo8175kl4-nodejs 
  janus-idp.io/tekton: eo8175kl4-nodejs
  backstage.io/kubernetes-id: eo8175kl4-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: eo8175kl4-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  